# ============================================================
# Smart Home Energy Monitoring Dashboard
#
# Real-time Energy Monitoring Platform
#
# Features
# - Live Monitoring
# - Alert Management
# - Device Health Tracking
# - Energy Analytics
# - Report Downloads
# - Executive Summary
#
# ============================================================

# pyrefly: ignore [missing-import]
import streamlit as st
import pandas as pd

# pyrefly: ignore [missing-import]
from streamlit_autorefresh import st_autorefresh

from api_client import (
    get_all_readings,
    get_latest,
    get_stats,
    get_device_health,
    get_system_health,
)

from charts import power_chart, energy_chart, appliance_chart, alert_chart

from analytics import calculate_metrics

# Uncomment once report generator is implemented
# from reports.pdf_generator import generate_pdf_report


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Smart Home Energy Monitoring", page_icon="⚡", layout="wide"
)

# Auto refresh dashboard every 5 seconds
st_autorefresh(interval=5000, key="energy_dashboard_refresh")

# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.title("⚡ Navigation")

page = st.sidebar.radio(
    "Select View", ["Overview", "Analytics", "Alerts", "Reports", "Devices"]
)

st.sidebar.markdown("---")

st.sidebar.info("Smart Home Energy Monitoring System v2.5")

# ============================================================
# LOAD DATA
# ============================================================

try:

    df = get_all_readings()
    # st.write("Columns:", df.columns.tolist())

    # st.write("Shape:", df.shape)

    # st.dataframe(df.head())

    if df.empty:
        st.warning("No energy readings available.")
        st.stop()

except Exception as e:

    st.error(f"Backend connection failed.\n\n{e}")

    st.stop()

latest = get_latest()

stats = get_stats()

metrics = calculate_metrics(df)

# ============================================================
# DATA PREPARATION
# ============================================================

if "timestamp" in df.columns:

    df["timestamp"] = pd.to_datetime(df["timestamp"])

    df["date"] = df["timestamp"].dt.date

# ============================================================
# HEADER
# ============================================================

st.title("🏠 Smart Home Energy Monitoring System")

st.caption("Real-Time Energy Analytics Platform")

# ============================================================
# LIVE ALERT BANNER
# ============================================================

latest_alert = latest["alert"]

if latest_alert == "OVERLOAD":

    st.error("🚨 CRITICAL OVERLOAD DETECTED")

elif latest_alert == "HIGH":

    st.warning("⚠ HIGH ENERGY CONSUMPTION DETECTED")

elif latest_alert == "WARNING":

    st.info("⚡ Elevated Energy Usage")

else:

    st.success("✅ System Operating Normally")

st.divider()

# ============================================================
# OVERVIEW PAGE
# ============================================================

if page == "Overview":

    st.subheader("⚡ Real-Time Monitoring")

    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Voltage", f"{latest['voltage']:.2f} V")

    col2.metric("Current", f"{latest['current']:.2f} A")

    col3.metric("Power", f"{latest['power']:.2f} W")

    col4.metric("Cost", f"₹ {latest['cost']:.2f}")

    st.divider()

    # ====================================================
    # DEVICE HEALTH CENTER
    # ====================================================

    st.subheader("🖥 Device Health Center")

    try:
        health = get_system_health()
    except Exception:
        health = {
            "mqtt_connected": False,
            "messages_received": 0,
            "seconds_since_last_message": None,
            "uptime_seconds": 0,
        }

    col1, col2, col3, col4 = st.columns(4)

    with col1:

        if health["mqtt_connected"]:

            st.success("MQTT ONLINE")

        else:

            st.error("MQTT OFFLINE")

    with col2:

        st.info(f"Messages: " f"{health['messages_received']}")

    with col3:

        st.info(f"Last Msg: " f"{health['seconds_since_last_message']} sec")

    with col4:

        st.info(f"Uptime: " f"{health['uptime_seconds']} sec")

    st.divider()

    # ====================================================
    # EXECUTIVE SUMMARY
    # ====================================================

    st.subheader("📋 Executive Summary")

    peak_row = df.loc[df["power"].idxmax()]

    total_alerts = len(df[df["alert"] != "NORMAL"])

    summary = f"""
    Today's energy monitoring indicates a total recorded energy usage of
    {metrics['total_energy']:.2f} kWh.

    The highest power consumption event was generated by
    {peak_row['appliance']} at
    {peak_row['power']:.2f} W.

    Total alert events detected:
    {total_alerts}

    Current estimated electricity cost:
    ₹ {metrics['total_cost']:.2f}

    System health status:
    Normal.
    """

    st.info(summary)

    st.divider()

    st.plotly_chart(power_chart(df), use_container_width=True)

    st.plotly_chart(energy_chart(df), use_container_width=True)

# ============================================================
# ANALYTICS PAGE
# ============================================================

elif page == "Analytics":

    st.subheader("📊 Energy Analytics")

    c1, c2, c3, c4 = st.columns(4)

    c1.metric("Peak Power", f"{metrics['max_power']:.2f} W")

    c2.metric("Average Power", f"{metrics['avg_power']:.2f} W")

    c3.metric("Total Energy", f"{metrics['total_energy']:.2f} kWh")

    c4.metric("Total Cost", f"₹ {metrics['total_cost']:.2f}")

    st.divider()

    left, right = st.columns(2)

    with left:

        st.plotly_chart(appliance_chart(df), use_container_width=True)

    with right:

        st.plotly_chart(alert_chart(df), use_container_width=True)

# ============================================================
# ALERTS PAGE
# ============================================================

elif page == "Alerts":

    st.subheader("🚦 Alert Monitoring Center")

    selected_alert = st.radio(
        "Filter Alert Level",
        ["ALL", "NORMAL", "WARNING", "HIGH", "OVERLOAD"],
        horizontal=True,
    )

    filtered_df = df.copy()

    if selected_alert != "ALL":

        filtered_df = df[df["alert"] == selected_alert]

    st.dataframe(
        filtered_df.sort_values(by="timestamp", ascending=False),
        use_container_width=True,
    )

# ============================================================
# REPORTS PAGE
# ============================================================

elif page == "Reports":

    st.subheader("📄 Reports & Exports")

    csv_data = df.to_csv(index=False).encode("utf-8")

    st.download_button(
        label="📥 Download CSV Report",
        data=csv_data,
        file_name="energy_report.csv",
        mime="text/csv",
    )

    st.markdown("---")

    st.info("PDF export will be enabled after integrating the report generator.")

    # Example Future Implementation
    #
    # if st.button(
    #     "Generate PDF Report"
    # ):
    #
    #     pdf_path = generate_pdf_report(df)
    #
    #     with open(
    #         pdf_path,
    #         "rb"
    #     ) as pdf_file:
    #
    #         st.download_button(
    #             "Download PDF",
    #             pdf_file,
    #             file_name="energy_report.pdf"
    #         )

# ============================================================
# DEVICES PAGE
# ============================================================

elif page == "Devices":

    st.subheader("🏠 Appliance Status Board")

    latest_appliances = df.sort_values("timestamp").groupby("appliance").tail(1)

    status_board = latest_appliances[["appliance", "power", "alert"]].sort_values(
        by="power", ascending=False
    )

    st.dataframe(status_board, use_container_width=True)

# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "Smart Home Energy Monitoring System | FastAPI + SQLite + Plotly + Streamlit"
)
